### ISSUE TITLE
Best Practice:  an IDE/plugin that will execute jinjasql templated code .

### ISSUE THREAD

**Issue by avishalom** [hashedin/jinjasql#27]
Specifically when developing dbt, can you write queries using this?
or is the only recommended way to wrap it in python?

**Comment by sripathikrishnan** [comment]
JinjaSQL was originally intended to run queries via python, so that is the recommended way. 

JinjaSQL and dbt are not related in any way, even though both the projects use the Jinja templating language. I am not too familiar with dbt, so don't know if JinjaSQL can be used within a dbt project. 

Having said that, can you explain your use case a bit more?

**Comment by sripathikrishnan** [comment]
Closing this issue, since there isn't a defect or a feature request. Thanks!
